### ISSUE TITLE
[BUG] Missing CORS headers on 403 error

### ISSUE THREAD

**Issue by pierreleripoll** [EPFL-ENAC/enacit4r-cdn#2]
Hello

when trying to access a missing file on CDN 
https://enacit4r-cdn.epfl.ch/lasur-swiss-proximity/2022-11-29/h3/7/66/46.pbf

The response doesn't have the CORS headers a successfull request has (eg https://enacit4r-cdn.epfl.ch/lasur-swiss-proximity/2022-11-29/h3/7/67/45.pbf) :

- access-control-allow-credentials: true
-  access-control-allow-headers: Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range
- access-control-allow-methods: GET
- access-control-allow-origin: *

This creates errors logs in my application
![image](https://user-images.githubusercontent.com/20055338/220375494-23051a8f-b44d-4a04-a894-344985c0f0f1.png)

Would it be possible to add thoses headers to 403 answers ?
Thanks !

**Comment by pierreleripoll** [comment]
I'm not sure if only the last header is important for my issue, but I don't see why the others are not supposed to be implemented on 403 error

**Comment by sbancal** [comment]
Maybe one way to get inspired from https://serverfault.com/a/745412/54845 to add headers on 40x responses ...
@guilbep @blueur you have an opinion on this ?

**Comment by guilbep** [comment]
@sbancal I think it's easier than that. We only need to add the 'always' --> https://www.lucaizzo.it/post/nginx-access-control-allow-origin-header-not-working-on-404-500-status-error

As explained in the nginx docs: http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header
to make the “add_header” function work on with all status code you have to add to it the “always” parameter.

For example if your configuration line is:

add_header 'Access-Control-Allow-Origin' '*';
Change it to:
add_header 'Access-Control-Allow-Origin' '*' always;

**Comment by sbancal** [comment]
Deployed. Behavior seems fixed. Thanks @guilbep ❤️ 

```bash
http -h https://enacit4r-cdn.epfl.ch/lasur-swiss-proximity/2022-11-29/h3/7/66/46.pbf
HTTP/1.1 403 Forbidden
Access-Control-Allow-Origin: *
Content-Length: 174
Content-Type: application/xml
Date: Fri, 24 Feb 2023 09:47:24 GMT
Server: nginx/1.23.3
```
